<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<TargetFramework>net9.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Confluent.Kafka" Version="2.10.0" />
		<PackageReference Include="EFCore.NamingConventions" Version="9.0.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.3" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
	</ItemGroup>

</Project>
